spring:
  config:
    import: optional:configserver:localhost:8888
  application:
    name: gateway-service
  cloud:
    config:
      name: gateway-service
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event/**
server:
  port: 80