spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 80