spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:10000/event-managment
    username: admin
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        exclude: prometheus

server:
  port: 9001