management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans
spring:
  cloud:
    config:
      name: gateway-service
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event/**