spring:
  profiles:
    active: development
  data:
    mongodb:
      username: root
      password: root
      database: user-service
      port: 27017
      host: localhost
server:
  port: 9011

jwt:
  secret-key: RandomKey

---
spring:
  data:
    mongodb:
      username: root
      passowrd: root
      database: test
      host: localhost
      port: 27017
      authentication-database: admin
  profiles:
    active: test

