server:
  port: ${PORT:9042}

spring:
  application:
    name: "payment-service"
  datasource:
    url: jdbc:postgresql://localhost:10000/payment-service
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
