spring:
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: development
  application:
    name: event-service
  cloud:
    config:
      name: event-service
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
