server:
  port: ${PORT:9032}

spring:
  application:
    name: "ticket-service"
  datasource:
    url: jdbc:postgresql://localhost:10000/ticket-service
    username: admin
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
